[functions]
  directory = "netlify/functions/" # Tells Netlify where your function code lives
  node_bundler = "esbuild"         # Uses a fast and modern bundler for your functions

# This redirect makes calling functions easier from your JavaScript
# Instead of '/.netlify/functions/get-tickets', you can use '/api/get-tickets'
[[redirects]]                             # [[redirects]]                    <-- Comment out or delete this line
  from = "/api/*"                         #   from = "/api/*"                <-- Comment out or delete this line
  to = "/.netlify/functions/:splat"        #   to = "/.netlify/functions/:splat"  <-- Comment out or delete this line
  status = 200 # OK status code for the redirect    #   status = 200                   <-- Comment out or delete this line
